import {
  useGetApiV1OccupancyRegistrationsByIdHouseholdMembersQuery,
  useGetApiV1OccupancyRegistrationsByIdQuery,
  useGetApiV1OccupancyRegistrationsByIdStatusHistoryQuery,
  useGetApiV1OccupancyRegistrationsByIdVehicleAssignmentsQuery,
  useGetApiV1OccupancyRegistrationsByIdWorkerAssignmentsQuery,
  useGetApiV1OccupancyRegistrationsQuery,
  usePostApiV1HouseholdMembersByIdDeactivateMutation,
  usePostApiV1OccupancyRegistrationsByIdActivateMutation,
  usePostApiV1OccupancyRegistrationsByIdHouseholdMembersMutation,
  usePostApiV1OccupancyRegistrationsByIdManagementRejectMutation,
  usePostApiV1OccupancyRegistrationsByIdManagementRequestCorrectionsMutation,
  usePostApiV1OccupancyRegistrationsByIdManagementVerifyMutation,
  usePostApiV1OccupancyRegistrationsByIdMoveOutMutation,
  usePostApiV1OccupancyRegistrationsByIdOwnerApproveMutation,
  usePostApiV1OccupancyRegistrationsByIdOwnerRejectMutation,
  usePostApiV1OccupancyRegistrationsByIdOwnerRequestCorrectionsMutation,
  usePostApiV1OccupancyRegistrationsByIdSubmitMutation,
  usePostApiV1OccupancyRegistrationsByIdVehicleAssignmentsMutation,
  usePostApiV1OccupancyRegistrationsByIdWorkerAssignmentsMutation,
  usePostApiV1OccupancyRegistrationsMutation,
  usePostApiV1VehicleAssignmentsByIdEndMutation,
  usePostApiV1WorkerAssignmentsByIdEndMutation,
  usePutApiV1HouseholdMembersByIdMutation,
  usePutApiV1HouseholdMembersByIdPrimaryPhotoMutation,
  usePutApiV1OccupancyRegistrationsByIdMutation,
  usePutApiV1OccupancyRegistrationsByIdPrimaryPhotoMutation,
} from '@/api/generated/mycondoApi';

// Friendlier re-exports of the OpenAPI-generated hooks (ADR-005). Domain/permission names use
// "OccupancyRegistration" to avoid colliding with this app's own multi-tenancy vocabulary; "Tenant
// Registration" is the label used everywhere in UI copy.
export const useCreateTenantRegistration = usePostApiV1OccupancyRegistrationsMutation;
export const useTenantRegistrations = useGetApiV1OccupancyRegistrationsQuery;
export const useTenantRegistration = useGetApiV1OccupancyRegistrationsByIdQuery;
export const useUpdateTenantRegistrationDraft = usePutApiV1OccupancyRegistrationsByIdMutation;
export const useSetTenantRegistrationPrimaryPhoto = usePutApiV1OccupancyRegistrationsByIdPrimaryPhotoMutation;
export const useSubmitTenantRegistration = usePostApiV1OccupancyRegistrationsByIdSubmitMutation;
export const useApproveTenantRegistrationByOwner = usePostApiV1OccupancyRegistrationsByIdOwnerApproveMutation;
export const useRequestTenantRegistrationCorrectionsByOwner =
  usePostApiV1OccupancyRegistrationsByIdOwnerRequestCorrectionsMutation;
export const useRejectTenantRegistrationByOwner = usePostApiV1OccupancyRegistrationsByIdOwnerRejectMutation;
export const useVerifyTenantRegistrationByManagement = usePostApiV1OccupancyRegistrationsByIdManagementVerifyMutation;
export const useRequestTenantRegistrationCorrectionsByManagement =
  usePostApiV1OccupancyRegistrationsByIdManagementRequestCorrectionsMutation;
export const useRejectTenantRegistrationByManagement =
  usePostApiV1OccupancyRegistrationsByIdManagementRejectMutation;
export const useActivateTenantRegistration = usePostApiV1OccupancyRegistrationsByIdActivateMutation;
export const useMoveOutTenantRegistration = usePostApiV1OccupancyRegistrationsByIdMoveOutMutation;
export const useTenantRegistrationStatusHistory = useGetApiV1OccupancyRegistrationsByIdStatusHistoryQuery;
export const useHouseholdMembers = useGetApiV1OccupancyRegistrationsByIdHouseholdMembersQuery;
export const useAddHouseholdMember = usePostApiV1OccupancyRegistrationsByIdHouseholdMembersMutation;
export const useUpdateHouseholdMember = usePutApiV1HouseholdMembersByIdMutation;
export const useDeactivateHouseholdMember = usePostApiV1HouseholdMembersByIdDeactivateMutation;
export const useSetHouseholdMemberPrimaryPhoto = usePutApiV1HouseholdMembersByIdPrimaryPhotoMutation;
export const useWorkerAssignments = useGetApiV1OccupancyRegistrationsByIdWorkerAssignmentsQuery;
export const useAssignWorker = usePostApiV1OccupancyRegistrationsByIdWorkerAssignmentsMutation;
export const useEndWorkerAssignment = usePostApiV1WorkerAssignmentsByIdEndMutation;
export const useVehicleAssignments = useGetApiV1OccupancyRegistrationsByIdVehicleAssignmentsQuery;
export const useAssignVehicle = usePostApiV1OccupancyRegistrationsByIdVehicleAssignmentsMutation;
export const useEndVehicleAssignment = usePostApiV1VehicleAssignmentsByIdEndMutation;
